# This is a basic workflow to help you get started with Actions

name: run earthquake heatmap

# Controls when the workflow will run
on:
  schedule:
    - cron: '* * * * 0' # once every sundays
  # push:
  #   branches:
  #     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run all scripts
        run: |
          python script/ingest/scrape.py
          python script/preparation/clean_data.py
          python script/preparation/location_data.py 
          python script/preparation/numeric_data.py 
          python script/visualization/visual_heatmap.py
        
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "update visuals" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
